# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    networks:
      - sonarnet
    restart: always
#    ports:
#      - 5432:5432
    environment:
      - POSTGRES_USER:sonar
      - POSTGRES_DB:sonar
      - POSTGRES_PASSWORD:sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    networks:
      - sonarnet
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  sonarqube:
    image: sonarqube
    networks:
      - sonarnet
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - db
    environment:
      - sonar.jdbc.username:sonar
      - sonar.jdbc.password:sonar
      - sonar.jdbc.url:jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
networks:
  sonarnet:
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
